# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/


# buildifier: disable=no-effect
ocaml_library(
    name = "basic_example",
    srcs = glob(["**/*.ml"]),
    compiler_flags = [
        "-no-alias-deps",
        "-w",
        "-49",
    ],
    visibility = ["PUBLIC"],
) if not host_info().os.is_windows else None
