# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

alias(
    name="bin",
    actual="//bin:ppx_usage_example",
    visibility=["PUBLIC"],
)

alias(
    name="lib",
    actual="//lib:ppx_usage_example",
    visibility=["PUBLIC"],
)

alias(
    name="test",
    actual="//test:ppx_usage_example",
    visibility=["PUBLIC"],
)
