# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/
alias(
    name="bin",
    actual="//bin:ocamllex_menhir_example",
    visibility=["PUBLIC"],
)

alias(
    name="lib",
    actual="//lib:ocamllex_menhir_example",
    visibility=["PUBLIC"],
)

alias(
    name="test",
    actual="//test:ocamllex_menhir_example",
    visibility=["PUBLIC"],
)
