# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

# buildifier: disable=no-effect
ocaml_binary(
    name = "basic_example",
    srcs = ["./basic_example_test.ml"],
    deps = [
        "//lib:basic_example",
        "//third-party:alcotest",
        "//third-party:qcheck-alcotest"
    ],
    compiler_flags = [
        "-cclib",
        "-lunixbyt",
        "-cclib",
        "-lunixnat",
    ],
    visibility = ["PUBLIC"],
)
