# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

# buildifier: disable=no-effect
ocaml_binary(
    name = "ppx",
    srcs = ["./driver.ml"],
    compiler_flags = [
        "-linkall",
    ],
    deps = ["//third-party:ppx_inline_alcotest",
    ],
)

# buildifier: disable=no-effect
ocaml_binary(
    name = "inline_test_runners",
    srcs = ["./inline_test_runners_test.ml"],
    deps = [
        "//lib:inline_test_runners",
        "//third-party:ppx_inline_alcotest",
        "//third-party:ppx_inline_alcotest.runner",
        "//third-party:alcotest",
        "//third-party:qcheck-alcotest"
    ],
    compiler_flags = [
        "-cclib",
        "-lunixbyt",
        "-cclib",
        "-lunixnat",
         "-ppx",
        "$(exe_target :ppx) --as-ppx",
    ],
    visibility = ["PUBLIC"],
)
