# A list of available rules and their signatures can be found here: https://buck2.build/docs/api/rules/

# buildifier: disable=no-effect
ocaml_binary(
    name = "inline_test_runners",
    srcs = ["./inline_test_runners_test.ml"],
    deps = [
        "//lib:inline_test_runners",
        "//third-party:alcotest",
        "//third-party:qcheck-alcotest"
    ],
    compiler_flags = [
        "-cclib",
        "-lunixbyt",
        "-cclib",
        "-lunixnat",
    ],
    visibility = ["PUBLIC"],
) if not host_info().os.is_windows else None
